/*
MIRROR: These constants are mirrored from backend
 */

const TERRAIN_TYPE_VOID = 0
const TERRAIN_TYPE_PLAINS = 1
const TERRAIN_TYPE_WALLS = 2
const TERRAIN_TYPE_HONEY_FIELD = 3
const TERRAIN_TYPE_WASTELAND = 4
const TERRAIN_TYPE_ICE_FIELD = 5
const TERRAIN_TYPE_THRONE = 6

/*
Terrain status for rendering
 */

const TERRAIN_STATUS_NORMAL = 0
const TERRAIN_STATUS_MOVE_TARGET = 1
const TERRAIN_STATUS_ATTACK_TARGET = 2
const TERRAIN_STATUS_SWAP_TARGET = 3

export {
  TERRAIN_TYPE_VOID,
  TERRAIN_TYPE_PLAINS,
  TERRAIN_TYPE_WALLS,
  TERRAIN_TYPE_HONEY_FIELD,
  TERRAIN_TYPE_WASTELAND,
  TERRAIN_TYPE_ICE_FIELD,
  TERRAIN_TYPE_THRONE,

  TERRAIN_STATUS_NORMAL,
  TERRAIN_STATUS_MOVE_TARGET,
  TERRAIN_STATUS_ATTACK_TARGET,
  TERRAIN_STATUS_SWAP_TARGET,
}
