/*
MIRROR: These constants are mirrored from backend
 */

const UNIT_TYPE_YOU = 1
const UNIT_TYPE_INFANTRY = 3

const UNIT_WEIGHT_YOU = 0
const UNIT_WEIGHT_INFANTRY = 0
const UNIT_WEIGHT_MAP = [
  -1,
  UNIT_WEIGHT_YOU,
  -1,
  UNIT_WEIGHT_INFANTRY,
]

const UNIT_MOVE_STEPS_YOU = 1
const UNIT_MOVE_STEPS_INFANTRY = 3

const UNIT_STATE_BIT_MOVED = 1

/*
Color constants
 */
const PLAYER_COLOR_TINT = [
  0, // unused
  0xFF6666,
  0x6666FF,
]

export {
  UNIT_TYPE_YOU,
  UNIT_TYPE_INFANTRY,

  UNIT_WEIGHT_YOU,
  UNIT_WEIGHT_INFANTRY,
  UNIT_WEIGHT_MAP,

  UNIT_MOVE_STEPS_YOU,
  UNIT_MOVE_STEPS_INFANTRY,

  UNIT_STATE_BIT_MOVED,

  PLAYER_COLOR_TINT,
}
