/*
MIRROR: These constants are mirrored from backend
 */

const UNIT_TYPE_QUEEN = 1
const UNIT_TYPE_INFANTRY = 3
const UNIT_TYPE_JET_CREW = 4
const UNIT_TYPE_WIZARD = 5
const UNIT_TYPE_TANK = 6
const UNIT_TYPE_MORTAR = 9

const UNIT_MAX_HP_QUEEN = 10
const UNIT_MAX_HP_INFANTRY = 10
const UNIT_MAX_HP_JET_CREW = 8
const UNIT_MAX_HP_WIZARD = 10
const UNIT_MAX_HP_TANK = 14
const UNIT_MAX_HP_MORTAR = 4
const UNIT_MAX_HP_MAP = [
  -1,
  UNIT_MAX_HP_QUEEN,
  -1,
  UNIT_MAX_HP_INFANTRY,
  UNIT_MAX_HP_JET_CREW,
  UNIT_MAX_HP_WIZARD,
  UNIT_MAX_HP_TANK,
  -1,
  -1,
  UNIT_MAX_HP_MORTAR,
]

const UNIT_WEIGHT_QUEEN = 0
const UNIT_WEIGHT_INFANTRY = 0
const UNIT_WEIGHT_JET_CREW = 0
const UNIT_WEIGHT_WIZARD = 0
const UNIT_WEIGHT_TANK = 1
const UNIT_WEIGHT_MORTAR = 0
const UNIT_WEIGHT_MAP = [
  -1,
  UNIT_WEIGHT_QUEEN,
  -1,
  UNIT_WEIGHT_INFANTRY,
  UNIT_WEIGHT_JET_CREW,
  UNIT_WEIGHT_WIZARD,
  UNIT_WEIGHT_TANK,
  -1,
  -1,
  UNIT_WEIGHT_MORTAR,
]

const MOVE_TYPE_NONE = 0
const MOVE_TYPE_GROUND = 1
const MOVE_TYPE_BLINK = 2
const UNIT_MOVE_TYPE_MAP = [
  -1,
  MOVE_TYPE_GROUND,
  -1,
  MOVE_TYPE_GROUND,
  MOVE_TYPE_GROUND,
  MOVE_TYPE_BLINK,
  MOVE_TYPE_GROUND,
  -1,
  -1,
  MOVE_TYPE_GROUND,
]

const UNIT_MOVE_RANGE_QUEEN = 1
const UNIT_MOVE_RANGE_INFANTRY = 3
const UNIT_MOVE_RANGE_JET_CREW = 6
const UNIT_MOVE_RANGE_WIZARD_MIN = 2
const UNIT_MOVE_RANGE_WIZARD_MAX = 3
const UNIT_MOVE_RANGE_TANK = 4
const UNIT_MOVE_RANGE_MORTAR = 4
const UNIT_MOVE_RANGE_MAP = [
  -1,
  UNIT_MOVE_RANGE_QUEEN,
  -1,
  UNIT_MOVE_RANGE_INFANTRY,
  UNIT_MOVE_RANGE_JET_CREW,
  UNIT_MOVE_RANGE_WIZARD_MAX,
  UNIT_MOVE_RANGE_TANK,
  -1,
  -1,
  UNIT_MOVE_RANGE_MORTAR,
]
const UNIT_MOVE_RANGE_MIN_MAP = [
  -1,
  0,
  -1,
  0,
  0,
  UNIT_MOVE_RANGE_WIZARD_MIN,
  0,
  -1,
  -1,
  0,
]

const ATTACK_TYPE_NONE = 0
const ATTACK_TYPE_GROUND = 1
const ATTACK_TYPE_AERIAL = 2
const UNIT_ATTACK_TYPE_MAP = [
  -1,
  ATTACK_TYPE_NONE,
  -1,
  ATTACK_TYPE_GROUND,
  ATTACK_TYPE_GROUND,
  ATTACK_TYPE_GROUND,
  ATTACK_TYPE_GROUND,
  -1,
  -1,
  ATTACK_TYPE_AERIAL,
]

const UNIT_ATTACK_RANGE_QUEEN = 0
const UNIT_ATTACK_RANGE_INFANTRY = 1
const UNIT_ATTACK_RANGE_JET_CREW = 1
const UNIT_ATTACK_RANGE_WIZARD = 2
const UNIT_ATTACK_RANGE_TANK = 1
const UNIT_ATTACK_RANGE_MORTAR_MIN = 2
const UNIT_ATTACK_RANGE_MORTAR_MAX = 3
const UNIT_ATTACK_RANGE_MAP = [
  -1,
  UNIT_ATTACK_RANGE_QUEEN,
  -1,
  UNIT_ATTACK_RANGE_INFANTRY,
  UNIT_ATTACK_RANGE_JET_CREW,
  UNIT_ATTACK_RANGE_WIZARD,
  UNIT_ATTACK_RANGE_TANK,
  -1,
  -1,
  UNIT_ATTACK_RANGE_MORTAR_MAX,
]
const UNIT_ATTACK_RANGE_MIN_MAP = [
  -1,
  0,
  -1,
  0,
  0,
  0,
  0,
  -1,
  -1,
  UNIT_ATTACK_RANGE_MORTAR_MIN,
]

const UNIT_STATE_BIT_MOVED = 1

/*
Color constants
 */
const PLAYER_COLOR_TINT = [
  0, // unused
  0xFF6666,
  0x6666FF,
  0x22AA00,
  0x8800CC,
]

const PLAYER_COLOR_NAME = [
  '',
  'Red',
  'Blue',
  'Green',
  'Purple',
]

export {
  UNIT_TYPE_QUEEN,
  UNIT_TYPE_INFANTRY,
  UNIT_TYPE_JET_CREW,
  UNIT_TYPE_WIZARD,
  UNIT_TYPE_TANK,
  UNIT_TYPE_MORTAR,

  UNIT_MAX_HP_QUEEN,
  UNIT_MAX_HP_INFANTRY,
  UNIT_MAX_HP_JET_CREW,
  UNIT_MAX_HP_WIZARD,
  UNIT_MAX_HP_TANK,
  UNIT_MAX_HP_MORTAR,
  UNIT_MAX_HP_MAP,

  UNIT_WEIGHT_MAP,

  MOVE_TYPE_NONE,
  MOVE_TYPE_GROUND,
  MOVE_TYPE_BLINK,
  UNIT_MOVE_TYPE_MAP,

  UNIT_MOVE_RANGE_MAP,
  UNIT_MOVE_RANGE_MIN_MAP,

  ATTACK_TYPE_NONE,
  ATTACK_TYPE_GROUND,
  ATTACK_TYPE_AERIAL,
  UNIT_ATTACK_TYPE_MAP,

  UNIT_ATTACK_RANGE_MAP,
  UNIT_ATTACK_RANGE_MIN_MAP,

  UNIT_STATE_BIT_MOVED,

  PLAYER_COLOR_TINT,
  PLAYER_COLOR_NAME,
}
