/*
This file specifies groups used by GameComms
 */

const GROUP_NONE = ''

const GROUP_WEBSOCKET = 'WS'
const GROUP_WEBSOCKET_LISTENERS = 'WS_L'

const GROUP_MAP_CONTROLLER = 'MAP_CTRL'
const GROUP_MAP_EVENT_LISTENERS = 'MAP_E_L'

export {
  GROUP_NONE,

  GROUP_WEBSOCKET,
  GROUP_WEBSOCKET_LISTENERS,

  GROUP_MAP_CONTROLLER,
  GROUP_MAP_EVENT_LISTENERS,
}
