/*
MIRROR: These constants are mirrored from backend
 */

const CMD_CHAT = 'CHAT'

const CMD_GAME_DATA = 'GAME_DATA'
const CMD_JOIN = 'JOIN'
const CMD_PING = 'PING'
const CMD_ERROR = 'ERROR'

const CMD_UNIT_STAY = 'UNIT_STAY'
const CMD_UNIT_MOVE = 'UNIT_MOVE'
const CMD_UNIT_ATTACK = 'UNIT_ATTACK'
const CMD_UNIT_MOVE_AND_ATTACK = 'UNIT_MOVE_ATTACK'

const CMD_END_TURN = 'END_TURN'

/*
FE specific commands
 */
const COMMS_TERRAIN_CLICK = 'TERRAIN_CLICK'
const COMMS_MAP_EVENT_END_TURN = 'MAP_END_TURN'

export {
  CMD_CHAT,

  CMD_GAME_DATA,
  CMD_JOIN,
  CMD_PING,
  CMD_ERROR,

  CMD_UNIT_STAY,
  CMD_UNIT_MOVE,
  CMD_UNIT_ATTACK,
  CMD_UNIT_MOVE_AND_ATTACK,

  CMD_END_TURN,

  COMMS_TERRAIN_CLICK,
  COMMS_MAP_EVENT_END_TURN,
}
